  INFO root [0x000069e0] [2019-06-13 02:02:30,279] - 
  INFO root [0x000069e0] [2019-06-13 02:02:30,280] - -----------------------------------------------------------------------------------------


  INFO root [0x000069e0] [2019-06-13 02:02:30,284] - Resmgr::initialize: OURO_ROOT=C:/Users/Black/Ouroboros/
  INFO root [0x000069e0] [2019-06-13 02:02:30,284] - Resmgr::initialize: OURO_RES_PATH=C:/Users/Black/Ouroboros/ouro/res/;C:/Users/Black/Ouroboros/assets/;C:/Users/Black/Ouroboros/assets/scripts/;C:/Users/Black/Ouroboros/assets/res/
  INFO root [0x000069e0] [2019-06-13 02:02:30,284] - Resmgr::initialize: OURO_BIN_PATH=C:/Users/Black/Ouroboros/ouro/bin/server/
  INFO root [0x000069e0] [2019-06-13 02:02:30,299] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.27.1 ( 192.168.27.1:20015 )
  INFO root [0x000069e0] [2019-06-13 02:02:30,300] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.27.1:20015, SOMAXCONN=128.
  INFO root [0x000069e0] [2019-06-13 02:02:30,303] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.27.1 ( 192.168.27.1:20005 )
  INFO root [0x000069e0] [2019-06-13 02:02:30,303] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.27.1:20005, SOMAXCONN=128.
  INFO root [0x000069e0] [2019-06-13 02:02:30,308] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.27.1 ( 192.168.27.1:4852 )
  INFO root [0x000069e0] [2019-06-13 02:02:30,308] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.27.1:4852, SOMAXCONN=128.
  INFO root [0x000069e0] [2019-06-13 02:02:30,308] - server-configs:
  INFO root [0x000069e0] [2019-06-13 02:02:30,308] - 	gameUpdateHertz : 10
  INFO root [0x000069e0] [2019-06-13 02:02:30,309] - 	entryScriptFile : ouromain
  INFO root [0x000069e0] [2019-06-13 02:02:30,309] - 	internalTcpAddr : 192.168.27.1:4852
  INFO root [0x000069e0] [2019-06-13 02:02:30,309] - 	externalTcpAddr : 192.168.27.1:20015
  INFO root [0x000069e0] [2019-06-13 02:02:30,309] - 	externalUdpAddr : 192.168.27.1:20005
  INFO root [0x000069e0] [2019-06-13 02:02:30,309] - 	componentID : 7001
  INFO root [0x000069e0] [2019-06-13 02:02:30,528] - Components::findLogger: found logger, addr:192.168.27.1:4720
  INFO root [0x000069e0] [2019-06-13 02:02:30,528] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x000069e0] [2019-06-13 02:02:30,528] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000069e0] [2019-06-13 02:02:30,533] - ---- baseapp Version: 2.5.0. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: 2A960BECD30E90E83AD965BB31769E2B. Config: Debug X86. Built: 02:54:19 May 23 2019. AppID: 7001. UID: 10103. PID: 28484 ----
  INFO root [0x000069e0] [2019-06-13 02:02:30,534] - Server Black: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz with 2097151kB RAM
  INFO root [0x000069e0] [2019-06-13 02:02:30,534] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000069e0] [2019-06-13 02:02:30,535] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000069e0] [2019-06-13 02:02:30,737] - Script::install(): is successfully, Python=(3.7.3 (default, Jun  7 2019, 22:47:18) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000069e0] [2019-06-13 02:02:30,737] - Script::install(): OUROxtra is successfully!
 DEBUG root [0x000069e0] [2019-06-13 02:02:31,051] - loaded entity-script:Account(1).
 DEBUG root [0x000069e0] [2019-06-13 02:02:31,051] - loaded entity-script:Avatar(2).
 DEBUG root [0x000069e0] [2019-06-13 02:02:31,056] - loaded entity-script:FirstEntity(6).
 DEBUG root [0x000069e0] [2019-06-13 02:02:31,056] - loaded entity-script:Scene(7).
 DEBUG root [0x000069e0] [2019-06-13 02:02:31,057] - loaded entity-script:Space(8).
 DEBUG root [0x000069e0] [2019-06-13 02:02:31,057] - loaded entity-script:Spaces(9).
 DEBUG root [0x000069e0] [2019-06-13 02:02:31,058] - loaded entity-script:SpaceDuplicate(10).
 DEBUG root [0x000069e0] [2019-06-13 02:02:31,058] - loaded entity-script:SpawnPoint(11).
  INFO root [0x000069e0] [2019-06-13 02:02:31,058] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000069e0] [2019-06-13 02:02:31,059] - TelnetServer server is running on port 40000
  INFO root [0x000069e0] [2019-06-13 02:02:31,434] - ---- baseapp is running ----
 DEBUG root [0x000069e0] [2019-06-13 02:02:31,434] - Components::process(): Request for the process of identity...
  WARN root [0x000069e0] [2019-06-13 02:02:37,732] - Forwarding logs to logger[192.168.27.1:4720/0/0/0]...
 ERROR root [0x000069e0] [2019-06-13 02:14:27,749] - KCPPacketSender::ikcp_send: send error! currPacketSize=59, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:14:27,750] - 192.168.27.1:54893: UDPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:14:27,766] - KCPPacketSender::ikcp_send: send error! currPacketSize=59, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:14:27,767] - 192.168.27.1:54893: UDPPacketSender::processSend(internal, 2): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:14:27,849] - KCPPacketSender::ikcp_send: send error! currPacketSize=59, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:14:27,850] - 192.168.27.1:54893: UDPPacketSender::processSend(internal, 3): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:14:27,866] - KCPPacketSender::ikcp_send: send error! currPacketSize=59, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:14:27,867] - 192.168.27.1:54893: UDPPacketSender::processSend(internal, 4): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:14:27,948] - KCPPacketSender::ikcp_send: send error! currPacketSize=59, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:14:27,950] - 192.168.27.1:54893: UDPPacketSender::processSend(internal, 5): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:14:27,966] - KCPPacketSender::ikcp_send: send error! currPacketSize=59, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:14:27,967] - 192.168.27.1:54893: UDPPacketSender::processSend(internal, 6): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:14:28,048] - KCPPacketSender::ikcp_send: send error! currPacketSize=59, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:14:28,049] - 192.168.27.1:54893: UDPPacketSender::processSend(internal, 7): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:14:28,066] - KCPPacketSender::ikcp_send: send error! currPacketSize=59, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:14:28,067] - 192.168.27.1:54893: UDPPacketSender::processSend(internal, 8): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:14:28,149] - KCPPacketSender::ikcp_send: send error! currPacketSize=59, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:14:28,150] - 192.168.27.1:54893: UDPPacketSender::processSend(internal, 9): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:14:28,166] - KCPPacketSender::ikcp_send: send error! currPacketSize=59, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:14:28,167] - 192.168.27.1:54893: UDPPacketSender::processSend(external, sendfailCount(10) >= 10): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:18:17,048] - KCPPacketSender::ikcp_send: send error! currPacketSize=75, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:18:17,050] - 192.168.27.1:65119: UDPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:18:17,060] - KCPPacketSender::ikcp_send: send error! currPacketSize=75, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:18:17,061] - 192.168.27.1:65119: UDPPacketSender::processSend(internal, 2): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:18:17,148] - KCPPacketSender::ikcp_send: send error! currPacketSize=75, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:18:17,149] - 192.168.27.1:65119: UDPPacketSender::processSend(internal, 3): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:18:17,160] - KCPPacketSender::ikcp_send: send error! currPacketSize=75, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:18:17,161] - 192.168.27.1:65119: UDPPacketSender::processSend(internal, 4): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:18:17,248] - KCPPacketSender::ikcp_send: send error! currPacketSize=75, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:18:17,250] - 192.168.27.1:65119: UDPPacketSender::processSend(internal, 5): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:18:17,260] - KCPPacketSender::ikcp_send: send error! currPacketSize=75, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:18:17,261] - 192.168.27.1:65119: UDPPacketSender::processSend(internal, 6): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:18:17,348] - KCPPacketSender::ikcp_send: send error! currPacketSize=75, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:18:17,350] - 192.168.27.1:65119: UDPPacketSender::processSend(internal, 7): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:18:17,360] - KCPPacketSender::ikcp_send: send error! currPacketSize=75, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:18:17,361] - 192.168.27.1:65119: UDPPacketSender::processSend(internal, 8): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:18:17,448] - KCPPacketSender::ikcp_send: send error! currPacketSize=75, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:18:17,449] - 192.168.27.1:65119: UDPPacketSender::processSend(internal, 9): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:18:17,460] - KCPPacketSender::ikcp_send: send error! currPacketSize=75, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:18:17,462] - 192.168.27.1:65119: UDPPacketSender::processSend(external, sendfailCount(10) >= 10): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:30:10,847] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:30:10,848] - 192.168.27.1:55399: UDPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:30:10,899] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:30:10,900] - 192.168.27.1:55399: UDPPacketSender::processSend(internal, 2): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:30:10,947] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:30:10,948] - 192.168.27.1:55399: UDPPacketSender::processSend(internal, 3): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:30:11,000] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:30:11,002] - 192.168.27.1:55399: UDPPacketSender::processSend(internal, 4): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:30:11,048] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:30:11,050] - 192.168.27.1:55399: UDPPacketSender::processSend(internal, 5): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:30:11,099] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:30:11,100] - 192.168.27.1:55399: UDPPacketSender::processSend(internal, 6): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:30:11,147] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:30:11,148] - 192.168.27.1:55399: UDPPacketSender::processSend(internal, 7): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:30:11,199] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:30:11,201] - 192.168.27.1:55399: UDPPacketSender::processSend(internal, 8): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:30:11,247] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:30:11,249] - 192.168.27.1:55399: UDPPacketSender::processSend(internal, 9): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 02:30:11,300] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 02:30:11,301] - 192.168.27.1:55399: UDPPacketSender::processSend(external, sendfailCount(10) >= 10): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:03:53,164] - PacketReader::processMessages: not found msgID=37552, msglen=31, from 192.168.27.1:55369/4/0/0.
 ERROR root [0x000069e0] [2019-06-13 03:14:18,644] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:14:18,646] - 192.168.27.1:51762: UDPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:14:18,679] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:14:18,680] - 192.168.27.1:51762: UDPPacketSender::processSend(internal, 2): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:14:18,745] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:14:18,746] - 192.168.27.1:51762: UDPPacketSender::processSend(internal, 3): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:14:18,779] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:14:18,780] - 192.168.27.1:51762: UDPPacketSender::processSend(internal, 4): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:14:18,847] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:14:18,849] - 192.168.27.1:51762: UDPPacketSender::processSend(internal, 5): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:14:18,879] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:14:18,880] - 192.168.27.1:51762: UDPPacketSender::processSend(internal, 6): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:14:18,943] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:14:18,945] - 192.168.27.1:51762: UDPPacketSender::processSend(internal, 7): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:14:18,979] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:14:18,980] - 192.168.27.1:51762: UDPPacketSender::processSend(internal, 8): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:14:19,044] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:14:19,046] - 192.168.27.1:51762: UDPPacketSender::processSend(internal, 9): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:14:19,079] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:14:19,082] - 192.168.27.1:51762: UDPPacketSender::processSend(external, sendfailCount(10) >= 10): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:37:23,844] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:37:23,845] - 192.168.27.1:60885: UDPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:37:23,898] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:37:23,899] - 192.168.27.1:60885: UDPPacketSender::processSend(internal, 2): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:37:23,943] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:37:23,944] - 192.168.27.1:60885: UDPPacketSender::processSend(internal, 3): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:37:23,998] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:37:24,001] - 192.168.27.1:60885: UDPPacketSender::processSend(internal, 4): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:37:24,042] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:37:24,044] - 192.168.27.1:60885: UDPPacketSender::processSend(internal, 5): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:37:24,098] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:37:24,103] - 192.168.27.1:60885: UDPPacketSender::processSend(internal, 6): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:37:24,144] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:37:24,145] - 192.168.27.1:60885: UDPPacketSender::processSend(internal, 7): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:37:24,199] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:37:24,200] - 192.168.27.1:60885: UDPPacketSender::processSend(internal, 8): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:37:24,244] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:37:24,246] - 192.168.27.1:60885: UDPPacketSender::processSend(internal, 9): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:37:24,298] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 03:37:24,299] - 192.168.27.1:60885: UDPPacketSender::processSend(external, sendfailCount(10) >= 10): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 03:40:20,948] - onRemoteMethodCallhandler::handle: Illegal access to entityID:46! proxyID=47
 ERROR root [0x000069e0] [2019-06-13 04:09:32,442] - KCPPacketSender::ikcp_send: send error! currPacketSize=43, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:09:32,443] - 192.168.27.1:56171: UDPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:09:32,519] - KCPPacketSender::ikcp_send: send error! currPacketSize=43, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:09:32,520] - 192.168.27.1:56171: UDPPacketSender::processSend(internal, 2): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:09:32,542] - KCPPacketSender::ikcp_send: send error! currPacketSize=43, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:09:32,543] - 192.168.27.1:56171: UDPPacketSender::processSend(internal, 3): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:09:32,619] - KCPPacketSender::ikcp_send: send error! currPacketSize=43, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:09:32,620] - 192.168.27.1:56171: UDPPacketSender::processSend(internal, 4): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:09:32,640] - KCPPacketSender::ikcp_send: send error! currPacketSize=43, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:09:32,642] - 192.168.27.1:56171: UDPPacketSender::processSend(internal, 5): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:09:32,719] - KCPPacketSender::ikcp_send: send error! currPacketSize=43, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:09:32,721] - 192.168.27.1:56171: UDPPacketSender::processSend(internal, 6): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:09:32,741] - KCPPacketSender::ikcp_send: send error! currPacketSize=43, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:09:32,743] - 192.168.27.1:56171: UDPPacketSender::processSend(internal, 7): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:09:32,819] - KCPPacketSender::ikcp_send: send error! currPacketSize=43, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:09:32,820] - 192.168.27.1:56171: UDPPacketSender::processSend(internal, 8): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:09:32,841] - KCPPacketSender::ikcp_send: send error! currPacketSize=43, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:09:32,843] - 192.168.27.1:56171: UDPPacketSender::processSend(internal, 9): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:09:32,919] - KCPPacketSender::ikcp_send: send error! currPacketSize=43, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:09:32,919] - 192.168.27.1:56171: UDPPacketSender::processSend(external, sendfailCount(10) >= 10): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:12:50,941] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:12:50,943] - 192.168.27.1:56242: UDPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:12:50,994] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:12:50,996] - 192.168.27.1:56242: UDPPacketSender::processSend(internal, 2): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:12:51,042] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:12:51,044] - 192.168.27.1:56242: UDPPacketSender::processSend(internal, 3): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:12:51,094] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:12:51,095] - 192.168.27.1:56242: UDPPacketSender::processSend(internal, 4): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:12:51,141] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:12:51,143] - 192.168.27.1:56242: UDPPacketSender::processSend(internal, 5): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:12:51,194] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:12:51,196] - 192.168.27.1:56242: UDPPacketSender::processSend(internal, 6): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:12:51,242] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:12:51,244] - 192.168.27.1:56242: UDPPacketSender::processSend(internal, 7): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:12:51,293] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:12:51,299] - 192.168.27.1:56242: UDPPacketSender::processSend(internal, 8): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:12:51,341] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:12:51,354] - 192.168.27.1:56242: UDPPacketSender::processSend(internal, 9): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:12:51,396] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:12:51,398] - 192.168.27.1:56242: UDPPacketSender::processSend(external, sendfailCount(10) >= 10): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:20:40,840] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:20:40,841] - 192.168.27.1:50396: UDPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:20:40,859] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:20:40,860] - 192.168.27.1:50396: UDPPacketSender::processSend(internal, 2): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:20:40,942] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:20:40,943] - 192.168.27.1:50396: UDPPacketSender::processSend(internal, 3): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:20:40,959] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:20:40,960] - 192.168.27.1:50396: UDPPacketSender::processSend(internal, 4): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:20:41,040] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:20:41,041] - 192.168.27.1:50396: UDPPacketSender::processSend(internal, 5): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:20:41,058] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:20:41,059] - 192.168.27.1:50396: UDPPacketSender::processSend(internal, 6): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:20:41,141] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:20:41,142] - 192.168.27.1:50396: UDPPacketSender::processSend(internal, 7): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:20:41,159] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:20:41,160] - 192.168.27.1:50396: UDPPacketSender::processSend(internal, 8): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:20:41,240] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:20:41,242] - 192.168.27.1:50396: UDPPacketSender::processSend(internal, 9): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:20:41,259] - KCPPacketSender::ikcp_send: send error! currPacketSize=27, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:20:41,260] - 192.168.27.1:50396: UDPPacketSender::processSend(external, sendfailCount(10) >= 10): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:23:16,088] - onRemoteMethodCallhandler::handle: Illegal access to entityID:54! proxyID=56
 ERROR root [0x000069e0] [2019-06-13 04:29:11,940] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:29:11,941] - 192.168.27.1:54129: UDPPacketSender::processSend(internal, 1): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:29:11,984] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:29:11,988] - 192.168.27.1:54129: UDPPacketSender::processSend(internal, 2): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:29:12,041] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:29:12,042] - 192.168.27.1:54129: UDPPacketSender::processSend(internal, 3): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:29:12,084] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:29:12,085] - 192.168.27.1:54129: UDPPacketSender::processSend(internal, 4): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:29:12,140] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:29:12,141] - 192.168.27.1:54129: UDPPacketSender::processSend(internal, 5): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:29:12,183] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:29:12,184] - 192.168.27.1:54129: UDPPacketSender::processSend(internal, 6): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:29:12,239] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:29:12,241] - 192.168.27.1:54129: UDPPacketSender::processSend(internal, 7): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:29:12,283] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:29:12,284] - 192.168.27.1:54129: UDPPacketSender::processSend(internal, 8): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:29:12,340] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:29:12,341] - 192.168.27.1:54129: UDPPacketSender::processSend(internal, 9): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:29:12,384] - KCPPacketSender::ikcp_send: send error! currPacketSize=67, ikcp_waitsnd=257, snd_wndsize=128
 ERROR root [0x000069e0] [2019-06-13 04:29:12,385] - 192.168.27.1:54129: UDPPacketSender::processSend(external, sendfailCount(10) >= 10): Exception occurred: REASON_RESOURCE_UNAVAILABLE
 ERROR root [0x000069e0] [2019-06-13 04:58:47,097] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=819098263328, lastReceivedTime=818907603092, inactivityExceptionPeriod=599484909)
  INFO root [0x000069e0] [2019-06-13 04:58:47,100] - The following logs sent to logger failed:
  WARN root [0x000069e0] [2019-06-13 04:58:47,100] - ==> [2019-06-13 04:58:47 096] TCPPacketReceiver::processPendingEvents(192.168.27.1:4720): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000069e0] [2019-06-13 04:58:47,101] - ==> [2019-06-13 04:58:47 098] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=819098263328, lastReceivedTime=818907603092, inactivityExceptionPeriod=599484909)
  WARN root [0x000069e0] [2019-06-13 04:58:47,267] - TCPPacketReceiver::processPendingEvents(192.168.27.1:4780): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000069e0] [2019-06-13 04:58:47,270] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=819099995287, lastReceivedTime=818925376344, inactivityExceptionPeriod=599484909)
  INFO root [0x000069e0] [2019-06-13 04:58:47,281] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000069e0] [2019-06-13 04:58:47,283] - onBaseAppShutDown: state=0
  INFO root [0x000069e0] [2019-06-13 04:58:47,284] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000069e0] [2019-06-13 04:58:47,284] - onBaseAppShutDown: state=1
  INFO root [0x000069e0] [2019-06-13 04:58:47,285] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000069e0] [2019-06-13 04:58:47,285] - onBaseAppShutDown: state=2
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,306] - SpawnPoint::~SpawnPoint(): 9
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,307] - SpawnPoint::~SpawnPoint(): 4
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,307] - SpawnPoint::~SpawnPoint(): 5
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,307] - SpawnPoint::~SpawnPoint(): 6
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,308] - SpawnPoint::~SpawnPoint(): 7
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,308] - SpawnPoint::~SpawnPoint(): 8
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,308] - SpawnPoint::~SpawnPoint(): 10
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,308] - SpawnPoint::~SpawnPoint(): 11
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,309] - SpawnPoint::~SpawnPoint(): 12
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,309] - SpawnPoint::~SpawnPoint(): 13
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,309] - SpawnPoint::~SpawnPoint(): 14
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,310] - SpawnPoint::~SpawnPoint(): 15
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,310] - SpawnPoint::~SpawnPoint(): 16
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,310] - SpawnPoint::~SpawnPoint(): 17
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,311] - SpawnPoint::~SpawnPoint(): 18
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,311] - SpawnPoint::~SpawnPoint(): 19
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,311] - SpawnPoint::~SpawnPoint(): 20
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,312] - SpawnPoint::~SpawnPoint(): 21
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,312] - SpawnPoint::~SpawnPoint(): 22
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,312] - SpawnPoint::~SpawnPoint(): 23
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,312] - SpawnPoint::~SpawnPoint(): 24
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,313] - SpawnPoint::~SpawnPoint(): 25
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,313] - SpawnPoint::~SpawnPoint(): 26
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,313] - SpawnPoint::~SpawnPoint(): 27
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,314] - SpawnPoint::~SpawnPoint(): 28
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,314] - SpawnPoint::~SpawnPoint(): 29
 ERROR root [0x000069e0] [2019-06-13 04:58:47,318] - PyGC::debugTracing(): Entity : leaked(3)
 ERROR root [0x000069e0] [2019-06-13 04:58:47,319] - PyGC::debugTracing(): EntityCall : leaked(2)
 ERROR root [0x000069e0] [2019-06-13 04:58:47,335] - EntityGarbages::~EntityGarbages(): leaked, size=3.
 ERROR root [0x000069e0] [2019-06-13 04:58:47,336] - 	--> leaked: Spaces(1).
 ERROR root [0x000069e0] [2019-06-13 04:58:47,338] - 	--> leaked: Space(2).
 ERROR root [0x000069e0] [2019-06-13 04:58:47,339] - 	--> leaked: Space(3).
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,340] - Spaces::~Spaces(): 1
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,341] - Space::~Space(): 2
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,341] - Space::~Space(): 3
  INFO root [0x000069e0] [2019-06-13 04:58:47,351] - Script::uninstall(): is successfully!
 DEBUG root [0x000069e0] [2019-06-13 04:58:47,352] - ThreadPool::destroy(): starting size 2.
  WARN root [0x000069e0] [2019-06-13 04:58:47,653] - ThreadPool::destroy(): waiting for thread(2)[0x1602c50,0x1602638,], try=1
  INFO root [0x00007878] [2019-06-13 04:58:51,672] - 
  INFO root [0x00007878] [2019-06-13 04:58:51,673] - -----------------------------------------------------------------------------------------


  INFO root [0x00007878] [2019-06-13 04:58:51,674] - Resmgr::initialize: OURO_ROOT=C:/Users/Black/Ouroboros/
  INFO root [0x00007878] [2019-06-13 04:58:51,674] - Resmgr::initialize: OURO_RES_PATH=C:/Users/Black/Ouroboros/ouro/res/;C:/Users/Black/Ouroboros/assets/;C:/Users/Black/Ouroboros/assets/scripts/;C:/Users/Black/Ouroboros/assets/res/
  INFO root [0x00007878] [2019-06-13 04:58:51,674] - Resmgr::initialize: OURO_BIN_PATH=C:/Users/Black/Ouroboros/ouro/bin/server/
  INFO root [0x00007878] [2019-06-13 04:58:51,688] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.27.1 ( 192.168.27.1:20015 )
  INFO root [0x00007878] [2019-06-13 04:58:51,689] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.27.1:20015, SOMAXCONN=128.
  INFO root [0x00007878] [2019-06-13 04:58:51,692] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.27.1 ( 192.168.27.1:20005 )
  INFO root [0x00007878] [2019-06-13 04:58:51,692] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.27.1:20005, SOMAXCONN=128.
  INFO root [0x00007878] [2019-06-13 04:58:51,696] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.27.1 ( 192.168.27.1:12413 )
  INFO root [0x00007878] [2019-06-13 04:58:51,696] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.27.1:12413, SOMAXCONN=128.
  INFO root [0x00007878] [2019-06-13 04:58:51,696] - server-configs:
  INFO root [0x00007878] [2019-06-13 04:58:51,696] - 	gameUpdateHertz : 10
  INFO root [0x00007878] [2019-06-13 04:58:51,696] - 	entryScriptFile : ouromain
  INFO root [0x00007878] [2019-06-13 04:58:51,697] - 	internalTcpAddr : 192.168.27.1:12413
  INFO root [0x00007878] [2019-06-13 04:58:51,697] - 	externalTcpAddr : 192.168.27.1:20015
  INFO root [0x00007878] [2019-06-13 04:58:51,697] - 	externalUdpAddr : 192.168.27.1:20005
  INFO root [0x00007878] [2019-06-13 04:58:51,697] - 	componentID : 7001
  INFO root [0x00007878] [2019-06-13 04:58:53,541] - ---- baseapp Version: 2.5.0. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: 2A960BECD30E90E83AD965BB31769E2B. Config: Debug X86. Built: 02:54:19 May 23 2019. AppID: 7001. UID: 10103. PID: 27424 ----
  INFO root [0x00007878] [2019-06-13 04:58:53,542] - Server Black: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz with 2097151kB RAM
  INFO root [0x00007878] [2019-06-13 04:58:53,542] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00007878] [2019-06-13 04:58:53,543] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00007878] [2019-06-13 04:58:53,761] - Script::install(): is successfully, Python=(3.7.3 (default, Jun  7 2019, 22:47:18) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00007878] [2019-06-13 04:58:53,761] - Script::install(): OUROxtra is successfully!
 DEBUG root [0x00007878] [2019-06-13 04:58:54,156] - loaded entity-script:Account(1).
 DEBUG root [0x00007878] [2019-06-13 04:58:54,157] - loaded entity-script:Avatar(2).
 DEBUG root [0x00007878] [2019-06-13 04:58:54,162] - loaded entity-script:FirstEntity(6).
 DEBUG root [0x00007878] [2019-06-13 04:58:54,163] - loaded entity-script:Scene(7).
 DEBUG root [0x00007878] [2019-06-13 04:58:54,164] - loaded entity-script:Space(8).
 DEBUG root [0x00007878] [2019-06-13 04:58:54,165] - loaded entity-script:Spaces(9).
 DEBUG root [0x00007878] [2019-06-13 04:58:54,166] - loaded entity-script:SpaceDuplicate(10).
 DEBUG root [0x00007878] [2019-06-13 04:58:54,167] - loaded entity-script:SpawnPoint(11).
  INFO root [0x00007878] [2019-06-13 04:58:54,167] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00007878] [2019-06-13 04:58:54,167] - TelnetServer server is running on port 40000
  INFO root [0x00007878] [2019-06-13 04:58:54,692] - ---- baseapp is running ----
 DEBUG root [0x00007878] [2019-06-13 04:58:54,693] - Components::process(): Request for the process of identity...
  WARN root [0x00007878] [2019-06-13 04:59:01,062] - EntityApp::checkTickPeriod: tick took 6370% (6.37 seconds)!
  INFO root [0x00007878] [2019-06-13 04:59:02,077] - Components::findComponents: find logger(1)...
  INFO root [0x00007878] [2019-06-13 04:59:02,118] - Components::findComponents: found logger, addr:192.168.27.1:12409
  INFO root [0x00007878] [2019-06-13 04:59:02,118] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00007878] [2019-06-13 04:59:02,118] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00007878] [2019-06-13 04:59:02,120] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00007878] [2019-06-13 04:59:02,225] - Components::findComponents: found dbmgr, addr:192.168.27.1:12410
  INFO root [0x00007878] [2019-06-13 04:59:02,225] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00007878] [2019-06-13 04:59:02,225] - Components::addComponent[dbmgr], uid=10103, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00007878] [2019-06-13 04:59:02,236] - Components::findComponents: found dbmgr, addr:192.168.27.1:12410
  WARN root [0x00007878] [2019-06-13 04:59:03,238] - Forwarding logs to logger[192.168.27.1:12409/0/0/0]...
 ERROR root [0x00007878] [2019-06-13 05:22:32,877] - onRemoteMethodCallhandler::handle: Illegal access to entityID:2030! proxyID=2031
 ERROR root [0x00007878] [2019-06-13 05:22:32,878] - Channel::processPackets(192.168.27.1:59198/1/16/0): channel[0x3b3a438] is condemn.
 ERROR root [0x00007878] [2019-06-13 05:24:32,457] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=834551870096, lastReceivedTime=834441279411, inactivityExceptionPeriod=599484525)
  INFO root [0x00007878] [2019-06-13 05:24:32,464] - The following logs sent to logger failed:
  WARN root [0x00007878] [2019-06-13 05:24:32,464] - ==> [2019-06-13 05:24:32 457] TCPPacketReceiver::processPendingEvents(192.168.27.1:12409): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00007878] [2019-06-13 05:24:32,465] - ==> [2019-06-13 05:24:32 458] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=834551870096, lastReceivedTime=834441279411, inactivityExceptionPeriod=599484525)
  WARN root [0x00007878] [2019-06-13 05:24:32,619] - TCPPacketReceiver::processPendingEvents(192.168.27.1:12410): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00007878] [2019-06-13 05:24:32,620] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=834553494716, lastReceivedTime=834443198091, inactivityExceptionPeriod=599484525)
  INFO root [0x00007878] [2019-06-13 05:24:32,622] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00007878] [2019-06-13 05:24:32,623] - onBaseAppShutDown: state=0
  INFO root [0x00007878] [2019-06-13 05:24:32,624] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00007878] [2019-06-13 05:24:32,624] - onBaseAppShutDown: state=1
  INFO root [0x00007878] [2019-06-13 05:24:32,624] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00007878] [2019-06-13 05:24:32,624] - onBaseAppShutDown: state=2
 DEBUG root [0x00007878] [2019-06-13 05:24:32,639] - SpawnPoint::~SpawnPoint(): 2009
 DEBUG root [0x00007878] [2019-06-13 05:24:32,639] - SpawnPoint::~SpawnPoint(): 2003
 DEBUG root [0x00007878] [2019-06-13 05:24:32,639] - SpawnPoint::~SpawnPoint(): 2004
 DEBUG root [0x00007878] [2019-06-13 05:24:32,640] - SpawnPoint::~SpawnPoint(): 2005
 DEBUG root [0x00007878] [2019-06-13 05:24:32,640] - SpawnPoint::~SpawnPoint(): 2006
 DEBUG root [0x00007878] [2019-06-13 05:24:32,640] - SpawnPoint::~SpawnPoint(): 2007
 DEBUG root [0x00007878] [2019-06-13 05:24:32,640] - SpawnPoint::~SpawnPoint(): 2008
 DEBUG root [0x00007878] [2019-06-13 05:24:32,640] - SpawnPoint::~SpawnPoint(): 2010
 DEBUG root [0x00007878] [2019-06-13 05:24:32,640] - SpawnPoint::~SpawnPoint(): 2011
 DEBUG root [0x00007878] [2019-06-13 05:24:32,641] - SpawnPoint::~SpawnPoint(): 2013
 DEBUG root [0x00007878] [2019-06-13 05:24:32,641] - SpawnPoint::~SpawnPoint(): 2014
 DEBUG root [0x00007878] [2019-06-13 05:24:32,641] - SpawnPoint::~SpawnPoint(): 2015
 DEBUG root [0x00007878] [2019-06-13 05:24:32,641] - SpawnPoint::~SpawnPoint(): 2016
 DEBUG root [0x00007878] [2019-06-13 05:24:32,642] - SpawnPoint::~SpawnPoint(): 2017
 DEBUG root [0x00007878] [2019-06-13 05:24:32,642] - SpawnPoint::~SpawnPoint(): 2018
 DEBUG root [0x00007878] [2019-06-13 05:24:32,642] - SpawnPoint::~SpawnPoint(): 2019
 DEBUG root [0x00007878] [2019-06-13 05:24:32,642] - SpawnPoint::~SpawnPoint(): 2020
 DEBUG root [0x00007878] [2019-06-13 05:24:32,642] - SpawnPoint::~SpawnPoint(): 2021
 DEBUG root [0x00007878] [2019-06-13 05:24:32,643] - SpawnPoint::~SpawnPoint(): 2022
 DEBUG root [0x00007878] [2019-06-13 05:24:32,643] - SpawnPoint::~SpawnPoint(): 2023
 DEBUG root [0x00007878] [2019-06-13 05:24:32,643] - SpawnPoint::~SpawnPoint(): 2024
 DEBUG root [0x00007878] [2019-06-13 05:24:32,643] - SpawnPoint::~SpawnPoint(): 2025
 DEBUG root [0x00007878] [2019-06-13 05:24:32,643] - SpawnPoint::~SpawnPoint(): 2026
 DEBUG root [0x00007878] [2019-06-13 05:24:32,645] - SpawnPoint::~SpawnPoint(): 2027
 DEBUG root [0x00007878] [2019-06-13 05:24:32,645] - SpawnPoint::~SpawnPoint(): 2028
 DEBUG root [0x00007878] [2019-06-13 05:24:32,645] - SpawnPoint::~SpawnPoint(): 2029
 ERROR root [0x00007878] [2019-06-13 05:24:32,647] - PyGC::debugTracing(): Entity : leaked(3)
 ERROR root [0x00007878] [2019-06-13 05:24:32,648] - PyGC::debugTracing(): EntityCall : leaked(2)
 ERROR root [0x00007878] [2019-06-13 05:24:32,658] - EntityGarbages::~EntityGarbages(): leaked, size=3.
 ERROR root [0x00007878] [2019-06-13 05:24:32,658] - 	--> leaked: Spaces(2001).
 ERROR root [0x00007878] [2019-06-13 05:24:32,660] - 	--> leaked: Space(2002).
 ERROR root [0x00007878] [2019-06-13 05:24:32,662] - 	--> leaked: Space(2012).
 DEBUG root [0x00007878] [2019-06-13 05:24:32,664] - Spaces::~Spaces(): 2001
 DEBUG root [0x00007878] [2019-06-13 05:24:32,664] - Space::~Space(): 2002
 DEBUG root [0x00007878] [2019-06-13 05:24:32,664] - Space::~Space(): 2012
  INFO root [0x00007878] [2019-06-13 05:24:32,672] - Script::uninstall(): is successfully!
 DEBUG root [0x00007878] [2019-06-13 05:24:32,672] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00007878] [2019-06-13 05:24:32,973] - ThreadPool::destroy(): waiting for thread(2)[0x187dfa0,0x187e008,], try=1
  INFO root [0x000053dc] [2019-06-13 05:24:36,842] - 
  INFO root [0x000053dc] [2019-06-13 05:24:36,842] - -----------------------------------------------------------------------------------------


  INFO root [0x000053dc] [2019-06-13 05:24:36,844] - Resmgr::initialize: OURO_ROOT=C:/Users/Black/Ouroboros/
  INFO root [0x000053dc] [2019-06-13 05:24:36,844] - Resmgr::initialize: OURO_RES_PATH=C:/Users/Black/Ouroboros/ouro/res/;C:/Users/Black/Ouroboros/assets/;C:/Users/Black/Ouroboros/assets/scripts/;C:/Users/Black/Ouroboros/assets/res/
  INFO root [0x000053dc] [2019-06-13 05:24:36,845] - Resmgr::initialize: OURO_BIN_PATH=C:/Users/Black/Ouroboros/ouro/bin/server/
  INFO root [0x000053dc] [2019-06-13 05:24:36,860] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.27.1 ( 192.168.27.1:20015 )
  INFO root [0x000053dc] [2019-06-13 05:24:36,860] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.27.1:20015, SOMAXCONN=128.
  INFO root [0x000053dc] [2019-06-13 05:24:36,865] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.27.1 ( 192.168.27.1:20005 )
  INFO root [0x000053dc] [2019-06-13 05:24:36,865] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.27.1:20005, SOMAXCONN=128.
  INFO root [0x000053dc] [2019-06-13 05:24:36,870] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.27.1 ( 192.168.27.1:1408 )
  INFO root [0x000053dc] [2019-06-13 05:24:36,870] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.27.1:1408, SOMAXCONN=128.
  INFO root [0x000053dc] [2019-06-13 05:24:36,871] - server-configs:
  INFO root [0x000053dc] [2019-06-13 05:24:36,871] - 	gameUpdateHertz : 10
  INFO root [0x000053dc] [2019-06-13 05:24:36,871] - 	entryScriptFile : ouromain
  INFO root [0x000053dc] [2019-06-13 05:24:36,871] - 	internalTcpAddr : 192.168.27.1:1408
  INFO root [0x000053dc] [2019-06-13 05:24:36,871] - 	externalTcpAddr : 192.168.27.1:20015
  INFO root [0x000053dc] [2019-06-13 05:24:36,872] - 	externalUdpAddr : 192.168.27.1:20005
  INFO root [0x000053dc] [2019-06-13 05:24:36,872] - 	componentID : 7001
  INFO root [0x000053dc] [2019-06-13 05:24:38,653] - ---- baseapp Version: 2.5.0. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: 2A960BECD30E90E83AD965BB31769E2B. Config: Debug X86. Built: 02:54:19 May 23 2019. AppID: 7001. UID: 10103. PID: 27604 ----
  INFO root [0x000053dc] [2019-06-13 05:24:38,654] - Server Black: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz with 2097151kB RAM
  INFO root [0x000053dc] [2019-06-13 05:24:38,654] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000053dc] [2019-06-13 05:24:38,655] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000053dc] [2019-06-13 05:24:38,886] - Script::install(): is successfully, Python=(3.7.3 (default, Jun  7 2019, 22:47:18) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000053dc] [2019-06-13 05:24:38,887] - Script::install(): OUROxtra is successfully!
 DEBUG root [0x000053dc] [2019-06-13 05:24:39,238] - loaded entity-script:Account(1).
 DEBUG root [0x000053dc] [2019-06-13 05:24:39,238] - loaded entity-script:Avatar(2).
 DEBUG root [0x000053dc] [2019-06-13 05:24:39,242] - loaded entity-script:FirstEntity(6).
 DEBUG root [0x000053dc] [2019-06-13 05:24:39,242] - loaded entity-script:Scene(7).
 DEBUG root [0x000053dc] [2019-06-13 05:24:39,243] - loaded entity-script:Space(8).
 DEBUG root [0x000053dc] [2019-06-13 05:24:39,243] - loaded entity-script:Spaces(9).
 DEBUG root [0x000053dc] [2019-06-13 05:24:39,244] - loaded entity-script:SpaceDuplicate(10).
 DEBUG root [0x000053dc] [2019-06-13 05:24:39,244] - loaded entity-script:SpawnPoint(11).
  INFO root [0x000053dc] [2019-06-13 05:24:39,244] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000053dc] [2019-06-13 05:24:39,245] - TelnetServer server is running on port 40000
  INFO root [0x000053dc] [2019-06-13 05:24:39,805] - ---- baseapp is running ----
 DEBUG root [0x000053dc] [2019-06-13 05:24:39,806] - Components::process(): Request for the process of identity...
  WARN root [0x000053dc] [2019-06-13 05:24:46,223] - EntityApp::checkTickPeriod: tick took 6417% (6.42 seconds)!
  INFO root [0x000053dc] [2019-06-13 05:24:47,246] - Components::findComponents: find logger(1)...
  INFO root [0x000053dc] [2019-06-13 05:24:47,288] - Components::findComponents: found logger, addr:192.168.27.1:1400
  INFO root [0x000053dc] [2019-06-13 05:24:47,289] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x000053dc] [2019-06-13 05:24:47,291] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000053dc] [2019-06-13 05:24:47,294] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000053dc] [2019-06-13 05:24:47,399] - Components::findComponents: found dbmgr, addr:192.168.27.1:1401
  INFO root [0x000053dc] [2019-06-13 05:24:47,400] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x000053dc] [2019-06-13 05:24:47,400] - Components::addComponent[dbmgr], uid=10103, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000053dc] [2019-06-13 05:24:47,421] - Components::findComponents: found dbmgr, addr:192.168.27.1:1401
  WARN root [0x000053dc] [2019-06-13 05:24:48,423] - Forwarding logs to logger[192.168.27.1:1400/0/0/0]...
 ERROR root [0x000053dc] [2019-06-13 05:28:15,381] - onRemoteMethodCallhandler::handle: Illegal access to entityID:2030! proxyID=2031
 ERROR root [0x000053dc] [2019-06-13 05:28:15,382] - Channel::processPackets(192.168.27.1:51562/1/16/0): channel[0x15295d8] is condemn.
 ERROR root [0x000053dc] [2019-06-13 05:30:09,621] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=837923514932, lastReceivedTime=837893570895, inactivityExceptionPeriod=599494245)
  INFO root [0x000053dc] [2019-06-13 05:30:09,629] - The following logs sent to logger failed:
  WARN root [0x000053dc] [2019-06-13 05:30:09,630] - ==> [2019-06-13 05:30:09 621] TCPPacketReceiver::processPendingEvents(192.168.27.1:1400): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000053dc] [2019-06-13 05:30:09,630] - ==> [2019-06-13 05:30:09 622] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=837923514932, lastReceivedTime=837893570895, inactivityExceptionPeriod=599494245)
  WARN root [0x000053dc] [2019-06-13 05:30:09,754] - TCPPacketReceiver::processPendingEvents(192.168.27.1:1401): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000053dc] [2019-06-13 05:30:09,755] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=837924848737, lastReceivedTime=837894387960, inactivityExceptionPeriod=599494245)
  INFO root [0x000053dc] [2019-06-13 05:30:09,761] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000053dc] [2019-06-13 05:30:09,765] - onBaseAppShutDown: state=0
  INFO root [0x000053dc] [2019-06-13 05:30:09,765] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000053dc] [2019-06-13 05:30:09,765] - onBaseAppShutDown: state=1
  INFO root [0x000053dc] [2019-06-13 05:30:09,765] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000053dc] [2019-06-13 05:30:09,765] - onBaseAppShutDown: state=2
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,783] - SpawnPoint::~SpawnPoint(): 2009
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,784] - SpawnPoint::~SpawnPoint(): 2003
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,784] - SpawnPoint::~SpawnPoint(): 2004
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,784] - SpawnPoint::~SpawnPoint(): 2005
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,785] - SpawnPoint::~SpawnPoint(): 2006
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,785] - SpawnPoint::~SpawnPoint(): 2007
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,786] - SpawnPoint::~SpawnPoint(): 2008
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,786] - SpawnPoint::~SpawnPoint(): 2010
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,786] - SpawnPoint::~SpawnPoint(): 2011
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,786] - SpawnPoint::~SpawnPoint(): 2013
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,787] - SpawnPoint::~SpawnPoint(): 2014
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,787] - SpawnPoint::~SpawnPoint(): 2015
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,788] - SpawnPoint::~SpawnPoint(): 2016
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,788] - SpawnPoint::~SpawnPoint(): 2017
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,788] - SpawnPoint::~SpawnPoint(): 2018
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,789] - SpawnPoint::~SpawnPoint(): 2019
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,789] - SpawnPoint::~SpawnPoint(): 2020
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,789] - SpawnPoint::~SpawnPoint(): 2021
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,789] - SpawnPoint::~SpawnPoint(): 2022
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,790] - SpawnPoint::~SpawnPoint(): 2023
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,790] - SpawnPoint::~SpawnPoint(): 2024
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,790] - SpawnPoint::~SpawnPoint(): 2025
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,790] - SpawnPoint::~SpawnPoint(): 2026
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,791] - SpawnPoint::~SpawnPoint(): 2027
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,791] - SpawnPoint::~SpawnPoint(): 2028
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,792] - SpawnPoint::~SpawnPoint(): 2029
 ERROR root [0x000053dc] [2019-06-13 05:30:09,795] - PyGC::debugTracing(): Entity : leaked(3)
 ERROR root [0x000053dc] [2019-06-13 05:30:09,796] - PyGC::debugTracing(): EntityCall : leaked(2)
 ERROR root [0x000053dc] [2019-06-13 05:30:09,809] - EntityGarbages::~EntityGarbages(): leaked, size=3.
 ERROR root [0x000053dc] [2019-06-13 05:30:09,809] - 	--> leaked: Spaces(2001).
 ERROR root [0x000053dc] [2019-06-13 05:30:09,813] - 	--> leaked: Space(2002).
 ERROR root [0x000053dc] [2019-06-13 05:30:09,815] - 	--> leaked: Space(2012).
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,817] - Spaces::~Spaces(): 2001
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,818] - Space::~Space(): 2002
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,818] - Space::~Space(): 2012
  INFO root [0x000053dc] [2019-06-13 05:30:09,827] - Script::uninstall(): is successfully!
 DEBUG root [0x000053dc] [2019-06-13 05:30:09,827] - ThreadPool::destroy(): starting size 2.
  WARN root [0x000053dc] [2019-06-13 05:30:10,128] - ThreadPool::destroy(): waiting for thread(2)[0x15b94f8,0x15b9700,], try=1
